# ArgoCD Helm Chart Values
# Note: Admin password is auto-generated by ArgoCD and managed by Ansible
# See: docs/implementation-argocd-gitlab-app.md for password configuration

server:
  service:
    type: ${service_type}
    servicePortHttp: ${http_port}
    servicePortHttps: ${https_port}
