apiVersion: v1
kind: List
items:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app.kubernetes.io/name: applications.argoproj.io
      app.kubernetes.io/part-of: argocd
    name: applications.argoproj.io
  spec:
    group: argoproj.io
    names:
      kind: Application
      listKind: ApplicationList
      plural: applications
      shortNames:
      - app
      - apps
      singular: application
    scope: Namespaced
    versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
            status:
              type: object
      served: true
      storage: true

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: argocd-server
    namespace: argocd
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: argocd-server
    template:
      metadata:
        labels:
          app.kubernetes.io/name: argocd-server
      spec:
        containers:
        - name: argocd-server
          image: argoproj/argocd:v2.7.4
          args:
          - /argocd-server
          - --staticassets
          - /shared/app
          ports:
          - containerPort: 8080
