apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: PruneLast=true
    argocd.argoproj.io/refresh: "60"
spec:
  project: default
  source:
    repoURL: https://github.com/ayee808/docker-k8s-hello-world
    targetRevision: HEAD
    path: api
    directory:
      exclude: '{**package-lock.json,**package.json}'
  destination:
    server: https://kubernetes.default.svc
    namespace: helloworld
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=true
      - PruneLast=true
      - Validate=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
